name: package_file_loader
description: Simple utility functions for loading a file from packages
version: 0.1.1
homepage: https://github.com/oliatienza/package_file_loader
repository: https://github.com/oliatienza/package_file_loader

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  build: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
